// AUTO-GENERATED by agents-inc — DO NOT EDIT

import type {
  SkillId as GlobalSkillId,
  AgentName as GlobalAgentName,
  Domain as GlobalDomain,
  Category as GlobalCategory,
} from '../../../../Users/danyj/.claude-src/config-types'

export type SkillId =
  | GlobalSkillId
  | 'api-baas-supabase'
  | 'api-database-postgresql'
  | 'api-messaging-webhooks'
  | 'api-observability-axiom-pino-sentry'
  | 'api-performance-api-performance'
  | 'infra-ci-cd-github-actions'
  | 'infra-config-setup-env'
  | 'infra-platform-vercel'
  | 'meta-config-stack-detect'
  | 'meta-design-composable-components'
  | 'meta-design-expressive-typescript'
  | 'meta-methodology-research-methodology'
  | 'meta-planning-api-planning'
  | 'meta-planning-web-planning'
  | 'meta-reviewing-api-reviewing'
  | 'meta-reviewing-infra-reviewing'
  | 'meta-reviewing-reviewing'
  | 'meta-reviewing-web-reviewing'
  | 'shared-security-auth-security'
  | 'shared-tooling-eslint-prettier'
  | 'shared-tooling-git-hooks'
  | 'shared-tooling-typescript-config'
  | 'vonatur-saas'
  | 'web-accessibility-web-accessibility'
  | 'web-dataviz-recharts'
  | 'web-error-handling-error-boundaries'
  | 'web-error-handling-result-types'
  | 'web-files-file-upload-patterns'
  | 'web-files-image-handling'
  | 'web-forms-react-hook-form'
  | 'web-forms-zod-validation'
  | 'web-framework-react'
  | 'web-meta-framework-nextjs'
  | 'web-mocks-msw'
  | 'web-performance-web-performance'
  | 'web-styling-cva'
  | 'web-styling-design-tokens'
  | 'web-styling-tailwind'
  | 'web-testing-playwright-e2e'
  | 'web-testing-react-testing-library'
  | 'web-testing-vitest'
  | 'web-ui-radix-ui'
  | 'web-ui-shadcn-ui'
  | 'web-ui-tanstack-table'
  | 'web-utilities-date-fns'

export type AgentName =
  | GlobalAgentName
  | 'api-developer'
  | 'api-researcher'
  | 'api-tester'
  | 'pm'
  | 'reviewer'
  | 'skill-summoner'
  | 'web-developer'
  | 'web-researcher'
  | 'web-tester'

export type SelectedAgentName =
  | 'api-developer'
  | 'api-researcher'
  | 'api-tester'
  | 'pm'
  | 'reviewer'
  | 'skill-summoner'
  | 'web-developer'
  | 'web-researcher'
  | 'web-tester'

export type ProjectAgentName = SelectedAgentName

export type Domain = GlobalDomain | 'api' | 'infra' | 'meta' | 'shared' | 'web'

export type Category =
  | GlobalCategory
  | 'api-baas'
  | 'api-messaging'
  | 'api-observability'
  | 'api-performance'
  | 'api-sql-engine'
  | 'infra-ci-cd'
  | 'infra-config'
  | 'infra-platform'
  | 'meta-design'
  | 'meta-methodology'
  | 'meta-planning'
  | 'meta-reviewing'
  | 'shared-lint'
  | 'shared-security'
  | 'shared-tooling'
  | 'web-accessibility'
  | 'web-dataviz'
  | 'web-e2e'
  | 'web-error-handling'
  | 'web-file-upload'
  | 'web-files'
  | 'web-form-library'
  | 'web-forms'
  | 'web-framework'
  | 'web-meta-framework'
  | 'web-mocking'
  | 'web-performance'
  | 'web-styling'
  | 'web-testing'
  | 'web-ui-components'
  | 'web-ui-kit'
  | 'web-utilities'

export type InstallMode = 'eject' | 'plugin' | 'mixed'

export type SkillConfig = {
  id: SkillId
  scope: 'project' | 'global'
  origin: string
  excluded?: boolean
}

export type AgentScopeConfig = {
  name: AgentName
  scope: 'project' | 'global'
  model?: 'sonnet' | 'opus' | 'haiku' | 'fable' | 'inherit'
  effort?: 'low' | 'medium' | 'high' | 'xhigh' | 'max'
  excluded?: boolean
}

export type SkillAssignment<S extends SkillId = SkillId> = S | { id: S; preloaded: boolean }

export type StackAgentConfig = Partial<Record<Category, SkillAssignment | SkillAssignment[]>>

export interface ProjectConfig {
  /** Project/plugin name (kebab-case) */
  name: string

  /** Project description */
  description?: string

  /** Per-agent configuration with scope */
  agents: AgentScopeConfig[]

  /** Per-skill configuration with scope and provenance */
  skills: SkillConfig[]

  /** Author handle (e.g., "@vince") */
  author?: string

  /** Stack configuration: agent -> category -> skill assignment */
  stack?: Partial<Record<ProjectAgentName, StackAgentConfig>>

  /** The marketplace this install reads skills from, as a path or URL */
  marketplace?: string

  /** The name that marketplace's manifest gives it, which plugins are registered under */
  marketplaceName?: string

  /** Agents source path or URL (when agents come from a different source than skills) */
  agentsSource?: string

  /** Selected domains from the wizard */
  selectedDomains?: Domain[]

  /** Tracked project installation paths (global config only) */
  projects?: string[]
}
